let vm = window.vm;

export const COUNTRY_CODE = [
  { label: vm.$t("CountryCode.Angola"), value: "244" },
  { label: vm.$t("CountryCode.Afghanistan"), value: "93" },
  { label: vm.$t("CountryCode.Albania"), value: "355" },
  { label: vm.$t("CountryCode.Algeria"), value: "213" },
  { label: vm.$t("CountryCode.Andorra"), value: "376" },
  { label: vm.$t("CountryCode.Anguilla"), value: "1264" },
  { label: vm.$t("CountryCode.Antigua_and_Barbuda"), value: "1268" },
  { label: vm.$t("CountryCode.Argentina"), value: "54" },
  { label: vm.$t("CountryCode.Armenia"), value: "374" },
  { label: vm.$t("CountryCode.Ascension"), value: "247" },
  { label: vm.$t("CountryCode.Australia"), value: "61" },
  { label: vm.$t("CountryCode.Austria"), value: "43" },
  { label: vm.$t("CountryCode.Azerbaijan"), value: "994" },
  { label: vm.$t("CountryCode.Bahamas"), value: "1242" },
  { label: vm.$t("CountryCode.Bahrain"), value: "973" },
  { label: vm.$t("CountryCode.Bangladesh"), value: "880" },
  { label: vm.$t("CountryCode.Barbados"), value: "1246" },
  { label: vm.$t("CountryCode.Belarus"), value: "375" },
  { label: vm.$t("CountryCode.Belgium"), value: "32" },
  { label: vm.$t("CountryCode.Belize"), value: "501" },
  { label: vm.$t("CountryCode.Benin"), value: "229" },
  { label: vm.$t("CountryCode.BermudaIs"), value: "1441" },
  { label: vm.$t("CountryCode.Bolivia"), value: "591" },
  { label: vm.$t("CountryCode.Botswana"), value: "267" },
  { label: vm.$t("CountryCode.Brazil"), value: "55" },
  { label: vm.$t("CountryCode.Brunei"), value: "673" },
  { label: vm.$t("CountryCode.Bulgaria"), value: "359" },
  { label: vm.$t("CountryCode.Burkina_faso"), value: "226" },
  { label: vm.$t("CountryCode.Burma"), value: "95" },
  { label: vm.$t("CountryCode.Burundi"), value: "257" },
  { label: vm.$t("CountryCode.Cameroon"), value: "237" },
  { label: vm.$t("CountryCode.Canada"), value: "1" },
  { label: vm.$t("CountryCode.Cayman_Is"), value: "1345" },
  { label: vm.$t("CountryCode.Central_African_Republic"), value: "236" },
  { label: vm.$t("CountryCode.Chad"), value: "235" },
  { label: vm.$t("CountryCode.Chile"), value: "56" },
  { label: vm.$t("CountryCode.China"), value: "86" },
  { label: vm.$t("CountryCode.Colombia"), value: "57" },
  { label: vm.$t("CountryCode.Congo"), value: "242" },
  { label: vm.$t("CountryCode.Cook_Is"), value: "682" },
  { label: vm.$t("CountryCode.Costa_Rica"), value: "506" },
  { label: vm.$t("CountryCode.Cuba"), value: "53" },
  { label: vm.$t("CountryCode.Cyprus"), value: "357" },
  { label: vm.$t("CountryCode.Czech_Republic"), value: "420" },
  { label: vm.$t("CountryCode.Denmark"), value: "45" },
  { label: vm.$t("CountryCode.Djibouti"), value: "253" },
  { label: vm.$t("CountryCode.Dominica_Rep"), value: "1890" },
  { label: vm.$t("CountryCode.Ecuador"), value: "593" },
  { label: vm.$t("CountryCode.Egypt"), value: "20" },
  { label: vm.$t("CountryCode.EISalvador"), value: "503" },
  { label: vm.$t("CountryCode.Estonia"), value: "372" },
  { label: vm.$t("CountryCode.Ethiopia"), value: "251" },
  { label: vm.$t("CountryCode.Fiji"), value: "679" },
  { label: vm.$t("CountryCode.Finland"), value: "358" },
  { label: vm.$t("CountryCode.France"), value: "33" },
  { label: vm.$t("CountryCode.French_Guiana"), value: "594" },
  { label: vm.$t("CountryCode.Gabon"), value: "241" },
  { label: vm.$t("CountryCode.Gambia"), value: "220" },
  { label: vm.$t("CountryCode.Georgia"), value: "995" },
  { label: vm.$t("CountryCode.Germany"), value: "49" },
  { label: vm.$t("CountryCode.Ghana"), value: "233" },
  { label: vm.$t("CountryCode.Gibraltar"), value: "350" },
  { label: vm.$t("CountryCode.Greece"), value: "30" },
  { label: vm.$t("CountryCode.Grenada"), value: "1809" },
  { label: vm.$t("CountryCode.Guam"), value: "1671" },
  { label: vm.$t("CountryCode.Guatemala"), value: "502" },
  { label: vm.$t("CountryCode.Guinea"), value: "224" },
  { label: vm.$t("CountryCode.Guyana"), value: "592" },
  { label: vm.$t("CountryCode.Haiti"), value: "509" },
  { label: vm.$t("CountryCode.Honduras"), value: "504" },
  { label: vm.$t("CountryCode.Hongkong"), value: "852" },
  { label: vm.$t("CountryCode.Hungary"), value: "36" },
  { label: vm.$t("CountryCode.Iceland"), value: "354" },
  { label: vm.$t("CountryCode.India"), value: "91" },
  { label: vm.$t("CountryCode.Indonesia"), value: "62" },
  { label: vm.$t("CountryCode.Iran"), value: "98" },
  { label: vm.$t("CountryCode.Iraq"), value: "964" },
  { label: vm.$t("CountryCode.Ireland"), value: "353" },
  { label: vm.$t("CountryCode.Israel"), value: "972" },
  { label: vm.$t("CountryCode.Italy"), value: "39" },
  { label: vm.$t("CountryCode.IvoryCoast"), value: "225" },
  { label: vm.$t("CountryCode.Jamaica"), value: "1876" },
  { label: vm.$t("CountryCode.Japan"), value: "81" },
  { label: vm.$t("CountryCode.Jordan"), value: "962" },
  { label: vm.$t("CountryCode.Kampuchea_Cambodia"), value: "855" },
  { label: vm.$t("CountryCode.Kazakstan"), value: "327" },
  { label: vm.$t("CountryCode.Kenya"), value: "254" },
  { label: vm.$t("CountryCode.Korea"), value: "82" },
  { label: vm.$t("CountryCode.Kuwait"), value: "965" },
  { label: vm.$t("CountryCode.Kyrgyzstan"), value: "331" },
  { label: vm.$t("CountryCode.Laos"), value: "856" },
  { label: vm.$t("CountryCode.Latvia"), value: "371" },
  { label: vm.$t("CountryCode.Lebanon"), value: "961" },
  { label: vm.$t("CountryCode.Lesotho"), value: "266" },
  { label: vm.$t("CountryCode.Liberia"), value: "231" },
  { label: vm.$t("CountryCode.Libya"), value: "218" },
  { label: vm.$t("CountryCode.Liechtenstein"), value: "423" },
  { label: vm.$t("CountryCode.Lithuania"), value: "370" },
  { label: vm.$t("CountryCode.Luxembourg"), value: "352" },
  { label: vm.$t("CountryCode.Macao"), value: "853" },
  { label: vm.$t("CountryCode.Madagascar"), value: "261" },
  { label: vm.$t("CountryCode.Malawi"), value: "265" },
  { label: vm.$t("CountryCode.Malaysia"), value: "60" },
  { label: vm.$t("CountryCode.Maldives"), value: "960" },
  { label: vm.$t("CountryCode.Mali"), value: "223" },
  { label: vm.$t("CountryCode.Malta"), value: "356" },
  { label: vm.$t("CountryCode.Mariana_Is"), value: "1670" },
  { label: vm.$t("CountryCode.Martinique"), value: "596" },
  { label: vm.$t("CountryCode.Mauritius"), value: "230" },
  { label: vm.$t("CountryCode.Mexico"), value: "52" },
  { label: vm.$t("CountryCode.Moldova_Republic_of"), value: "373" },
  { label: vm.$t("CountryCode.Monaco"), value: "377" },
  { label: vm.$t("CountryCode.Mongolia"), value: "976" },
  { label: vm.$t("CountryCode.Montserrat_Is"), value: "1664" },
  { label: vm.$t("CountryCode.Morocco"), value: "212" },
  { label: vm.$t("CountryCode.Mozambique"), value: "258" },
  { label: vm.$t("CountryCode.Namibia"), value: "264" },
  { label: vm.$t("CountryCode.Nauru"), value: "674" },
  { label: vm.$t("CountryCode.Nepal"), value: "977" },
  { label: vm.$t("CountryCode.Netheriands_Antilles"), value: "599" },
  { label: vm.$t("CountryCode.Netherlands"), value: "31" },
  { label: vm.$t("CountryCode.NewZealand"), value: "64" },
  { label: vm.$t("CountryCode.Nicaragua"), value: "505" },
  { label: vm.$t("CountryCode.Niger"), value: "227" },
  { label: vm.$t("CountryCode.Nigeria"), value: "234" },
  { label: vm.$t("CountryCode.North_Korea"), value: "850" },
  { label: vm.$t("CountryCode.Norway"), value: "47" },
  { label: vm.$t("CountryCode.Oman"), value: "968" },
  { label: vm.$t("CountryCode.Pakistan"), value: "92" },
  { label: vm.$t("CountryCode.Panama"), value: "507" },
  { label: vm.$t("CountryCode.Papua_New_Cuinea"), value: "675" },
  { label: vm.$t("CountryCode.Paraguay"), value: "595" },
  { label: vm.$t("CountryCode.Peru"), value: "51" },
  { label: vm.$t("CountryCode.Philippines"), value: "63" },
  { label: vm.$t("CountryCode.Poland"), value: "48" },
  { label: vm.$t("CountryCode.French_Polynesia"), value: "689" },
  { label: vm.$t("CountryCode.Portugal"), value: "351" },
  { label: vm.$t("CountryCode.PuertoRico"), value: "1787" },
  { label: vm.$t("CountryCode.Qatar"), value: "974" },
  { label: vm.$t("CountryCode.Reunion"), value: "262" },
  { label: vm.$t("CountryCode.Romania"), value: "40" },
  { label: vm.$t("CountryCode.Russia"), value: "7" },
  { label: vm.$t("CountryCode.Saint_Lueia"), value: "1758" },
  { label: vm.$t("CountryCode.Saint_Vincent"), value: "1784" },
  { label: vm.$t("CountryCode.Samoa_Eastern"), value: "684" },
  { label: vm.$t("CountryCode.Samoa_Western"), value: "685" },
  { label: vm.$t("CountryCode.San_Marino"), value: "378" },
  { label: vm.$t("CountryCode.Sao_Tome_and_Principe"), value: "239" },
  { label: vm.$t("CountryCode.Saudi_Arabia"), value: "966" },
  { label: vm.$t("CountryCode.Senegal"), value: "221" },
  { label: vm.$t("CountryCode.Seychelles"), value: "248" },
  { label: vm.$t("CountryCode.Sierra_Leone"), value: "232" },
  { label: vm.$t("CountryCode.Singapore"), value: "65" },
  { label: vm.$t("CountryCode.Slovakia"), value: "421" },
  { label: vm.$t("CountryCode.Slovenia"), value: "386" },
  { label: vm.$t("CountryCode.Solomon_Is"), value: "677" },
  { label: vm.$t("CountryCode.Somali"), value: "252" },
  { label: vm.$t("CountryCode.South_Africa"), value: "27" },
  { label: vm.$t("CountryCode.Spain"), value: "34" },
  { label: vm.$t("CountryCode.Sri_Lanka"), value: "94" },
  { label: vm.$t("CountryCode.StLucia"), value: "1758" },
  { label: vm.$t("CountryCode.StVincent"), value: "1784" },
  { label: vm.$t("CountryCode.Sudan"), value: "249" },
  { label: vm.$t("CountryCode.Suriname"), value: "597" },
  { label: vm.$t("CountryCode.Swaziland"), value: "268" },
  { label: vm.$t("CountryCode.Sweden"), value: "46" },
  { label: vm.$t("CountryCode.Switzerland"), value: "41" },
  { label: vm.$t("CountryCode.Syriaw"), value: "963" },
  { label: vm.$t("CountryCode.Taiwan"), value: "886" },
  { label: vm.$t("CountryCode.Tajikstan"), value: "992" },
  { label: vm.$t("CountryCode.Tanzania"), value: "255" },
  { label: vm.$t("CountryCode.Thailand"), value: "66" },
  { label: vm.$t("CountryCode.Togo"), value: "228" },
  { label: vm.$t("CountryCode.Tonga"), value: "676" },
  { label: vm.$t("CountryCode.Trinidad_and_Tobago"), value: "1809" },
  { label: vm.$t("CountryCode.Tunisia"), value: "216" },
  { label: vm.$t("CountryCode.Turkey"), value: "90" },
  { label: vm.$t("CountryCode.Turkmenistan"), value: "993" },
  { label: vm.$t("CountryCode.Uganda"), value: "256" },
  { label: vm.$t("CountryCode.Ukraine"), value: "380" },
  { label: vm.$t("CountryCode.United_Arab_Emirates"), value: "971" },
  { label: vm.$t("CountryCode.United_Kiongdom"), value: "44" },
  { label: vm.$t("CountryCode.United_States_of_America"), value: "1" },
  { label: vm.$t("CountryCode.Uruguay"), value: "598" },
  { label: vm.$t("CountryCode.Uzbekistan"), value: "233" },
  { label: vm.$t("CountryCode.Venezuela"), value: "58" },
  { label: vm.$t("CountryCode.Vietnam"), value: "84" },
  { label: vm.$t("CountryCode.Yemen"), value: "967" },
  { label: vm.$t("CountryCode.Yugoslavia"), value: "381" },
  { label: vm.$t("CountryCode.South_Africa"), value: "27" },
  { label: vm.$t("CountryCode.Zimbabwe"), value: "263" },
  { label: vm.$t("CountryCode.Zaire"), value: "243" },
  { label: vm.$t("CountryCode.Zambia"), value: "260" }
];

export const CURRENCY_CODE = [
  { label: "AED " + vm.$t("Currency.AED"), value: "AED" },
  { label: "AFN " + vm.$t("Currency.AFN"), value: "AFN" },
  { label: "ALL " + vm.$t("Currency.ALL"), value: "ALL" },
  { label: "AMD " + vm.$t("Currency.AMD"), value: "AMD" },
  { label: "ANG " + vm.$t("Currency.ANG"), value: "ANG" },
  { label: "AOA " + vm.$t("Currency.AOA"), value: "AOA" },
  { label: "ARS " + vm.$t("Currency.ARS"), value: "ARS" },
  { label: "AUD " + vm.$t("Currency.AUD"), value: "AUD" },
  { label: "AWG " + vm.$t("Currency.AWG"), value: "AWG" },
  { label: "AZN " + vm.$t("Currency.AZN"), value: "AZN" },
  { label: "BAM " + vm.$t("Currency.BAM"), value: "BAM" },
  { label: "BBD " + vm.$t("Currency.BBD"), value: "BBD" },
  { label: "BDT " + vm.$t("Currency.BDT"), value: "BDT" },
  { label: "BGN " + vm.$t("Currency.BGN"), value: "BGN" },
  { label: "BHD " + vm.$t("Currency.BHD"), value: "BHD" },
  { label: "BIF " + vm.$t("Currency.BIF"), value: "BIF" },
  { label: "BMD " + vm.$t("Currency.BMD"), value: "BMD" },
  { label: "BND " + vm.$t("Currency.BND"), value: "BND" },
  { label: "BOB " + vm.$t("Currency.BOB"), value: "BOB" },
  { label: "BRL " + vm.$t("Currency.BRL"), value: "BRL" },
  { label: "BSD " + vm.$t("Currency.BSD"), value: "BSD" },
  { label: "BTN " + vm.$t("Currency.BTN"), value: "BTN" },
  { label: "BWP " + vm.$t("Currency.BWP"), value: "BWP" },
  { label: "BYN " + vm.$t("Currency.BYN"), value: "BYN" },
  { label: "BYR " + vm.$t("Currency.BYR"), value: "BYR" },
  { label: "BZD " + vm.$t("Currency.BZD"), value: "BZD" },
  { label: "CAD " + vm.$t("Currency.CAD"), value: "CAD" },
  { label: "CDF " + vm.$t("Currency.CDF"), value: "CDF" },
  { label: "CHF " + vm.$t("Currency.CHF"), value: "CHF" },
  { label: "CLF " + vm.$t("Currency.CLF"), value: "CLF" },
  { label: "CLP " + vm.$t("Currency.CLP"), value: "CLP" },
  { label: "CNY " + vm.$t("Currency.CNY"), value: "CNY" },
  { label: "COP " + vm.$t("Currency.COP"), value: "COP" },
  { label: "CRC " + vm.$t("Currency.CRC"), value: "CRC" },
  { label: "CUP " + vm.$t("Currency.CUP"), value: "CUP" },
  { label: "CVE " + vm.$t("Currency.CVE"), value: "CVE" },
  { label: "CZK " + vm.$t("Currency.CZK"), value: "CZK" },
  { label: "DJF " + vm.$t("Currency.DJF"), value: "DJF" },
  { label: "DKK " + vm.$t("Currency.DKK"), value: "DKK" },
  { label: "DOP " + vm.$t("Currency.DOP"), value: "DOP" },
  { label: "DZD " + vm.$t("Currency.DZD"), value: "DZD" },
  { label: "EGP " + vm.$t("Currency.EGP"), value: "EGP" },
  { label: "ERN " + vm.$t("Currency.ERN"), value: "ERN" },
  { label: "ETB " + vm.$t("Currency.ETB"), value: "ETB" },
  { label: "EUR " + vm.$t("Currency.EUR"), value: "EUR" },
  { label: "FJD " + vm.$t("Currency.FJD"), value: "FJD" },
  { label: "FKP " + vm.$t("Currency.FKP"), value: "FKP" },
  { label: "GBP " + vm.$t("Currency.GBP"), value: "GBP" },
  { label: "GEL " + vm.$t("Currency.GEL"), value: "GEL" },
  { label: "GHS " + vm.$t("Currency.GHS"), value: "GHS" },
  { label: "GIP " + vm.$t("Currency.GIP"), value: "GIP" },
  { label: "GMD " + vm.$t("Currency.GMD"), value: "GMD" },
  { label: "GNF " + vm.$t("Currency.GNF"), value: "GNF" },
  { label: "GTQ " + vm.$t("Currency.GTQ"), value: "GTQ" },
  { label: "GYD " + vm.$t("Currency.GYD"), value: "GYD" },
  { label: "HKD " + vm.$t("Currency.HKD"), value: "HKD" },
  { label: "HNL " + vm.$t("Currency.HNL"), value: "HNL" },
  { label: "HRK " + vm.$t("Currency.HRK"), value: "HRK" },
  { label: "HTG " + vm.$t("Currency.HTG"), value: "HTG" },
  { label: "HUF " + vm.$t("Currency.HUF"), value: "HUF" },
  { label: "IDR " + vm.$t("Currency.IDR"), value: "IDR" },
  { label: "ILS " + vm.$t("Currency.ILS"), value: "ILS" },
  { label: "INR " + vm.$t("Currency.INR"), value: "INR" },
  { label: "IQD " + vm.$t("Currency.IQD"), value: "IQD" },
  { label: "IRR " + vm.$t("Currency.IRR"), value: "IRR" },
  { label: "ISK " + vm.$t("Currency.ISK"), value: "ISK" },
  { label: "JMD " + vm.$t("Currency.JMD"), value: "JMD" },
  { label: "JOD " + vm.$t("Currency.JOD"), value: "JOD" },
  { label: "JPY " + vm.$t("Currency.JPY"), value: "JPY" },
  { label: "KES " + vm.$t("Currency.KES"), value: "KES" },
  { label: "KGS " + vm.$t("Currency.KGS"), value: "KGS" },
  { label: "KHR " + vm.$t("Currency.KHR"), value: "KHR" },
  { label: "KMF " + vm.$t("Currency.KMF"), value: "KMF" },
  { label: "KPW " + vm.$t("Currency.KPW"), value: "KPW" },
  { label: "KRW " + vm.$t("Currency.KRW"), value: "KRW" },
  { label: "KWD " + vm.$t("Currency.KWD"), value: "KWD" },
  { label: "KYD " + vm.$t("Currency.KYD"), value: "KYD" },
  { label: "KZT " + vm.$t("Currency.KZT"), value: "KZT" },
  { label: "LAK " + vm.$t("Currency.LAK"), value: "LAK" },
  { label: "LBP " + vm.$t("Currency.LBP"), value: "LBP" },
  { label: "LKR " + vm.$t("Currency.LKR"), value: "LKR" },
  { label: "LRD " + vm.$t("Currency.LRD"), value: "LRD" },
  { label: "LSL " + vm.$t("Currency.LSL"), value: "LSL" },
  { label: "LYD " + vm.$t("Currency.LYD"), value: "LYD" },
  { label: "MAD " + vm.$t("Currency.MAD"), value: "MAD" },
  { label: "MDL " + vm.$t("Currency.MDL"), value: "MDL" },
  { label: "MGA " + vm.$t("Currency.MGA"), value: "MGA" },
  { label: "MKD " + vm.$t("Currency.MKD"), value: "MKD" },
  { label: "MMK " + vm.$t("Currency.MMK"), value: "MMK" },
  { label: "MNT " + vm.$t("Currency.MNT"), value: "MNT" },
  { label: "MOP " + vm.$t("Currency.MOP"), value: "MOP" },
  { label: "MRO " + vm.$t("Currency.MRO"), value: "MRO" },
  { label: "MUR " + vm.$t("Currency.MUR"), value: "MUR" },
  { label: "MVR " + vm.$t("Currency.MVR"), value: "MVR" },
  { label: "MWK " + vm.$t("Currency.MWK"), value: "MWK" },
  { label: "MXN " + vm.$t("Currency.MXN"), value: "MXN" },
  { label: "MXV " + vm.$t("Currency.MXV"), value: "MXV" },
  { label: "MYR " + vm.$t("Currency.MYR"), value: "MYR" },
  { label: "MZN " + vm.$t("Currency.MZN"), value: "MZN" },
  { label: "NAD " + vm.$t("Currency.NAD"), value: "NAD" },
  { label: "NGN " + vm.$t("Currency.NGN"), value: "NGN" },
  { label: "NIO " + vm.$t("Currency.NIO"), value: "NIO" },
  { label: "NOK " + vm.$t("Currency.NOK"), value: "NOK" },
  { label: "NPR " + vm.$t("Currency.NPR"), value: "NPR" },
  { label: "NZD " + vm.$t("Currency.NZD"), value: "NZD" },
  { label: "OMR " + vm.$t("Currency.OMR"), value: "OMR" },
  { label: "PAB " + vm.$t("Currency.PAB"), value: "PAB" },
  { label: "PEN " + vm.$t("Currency.PEN"), value: "PEN" },
  { label: "PGK " + vm.$t("Currency.PGK"), value: "PGK" },
  { label: "PHP " + vm.$t("Currency.PHP"), value: "PHP" },
  { label: "PKR " + vm.$t("Currency.PKR"), value: "PKR" },
  { label: "PLN " + vm.$t("Currency.PLN"), value: "PLN" },
  { label: "PYG " + vm.$t("Currency.PYG"), value: "PYG" },
  { label: "QAR " + vm.$t("Currency.QAR"), value: "QAR" },
  { label: "RON " + vm.$t("Currency.RON"), value: "RON" },
  { label: "RSD " + vm.$t("Currency.RSD"), value: "RSD" },
  { label: "RUB " + vm.$t("Currency.RUB"), value: "RUB" },
  { label: "RWF " + vm.$t("Currency.RWF"), value: "RWF" },
  { label: "SAR " + vm.$t("Currency.SAR"), value: "SAR" },
  { label: "SBD " + vm.$t("Currency.SBD"), value: "SBD" },
  { label: "SCR " + vm.$t("Currency.SCR"), value: "SCR" },
  { label: "SDG " + vm.$t("Currency.SDG"), value: "SDG" },
  { label: "SEK " + vm.$t("Currency.SEK"), value: "SEK" },
  { label: "SGD " + vm.$t("Currency.SGD"), value: "SGD" },
  { label: "SHP " + vm.$t("Currency.SHP"), value: "SHP" },
  { label: "SLL " + vm.$t("Currency.SLL"), value: "SLL" },
  { label: "SOS " + vm.$t("Currency.SOS"), value: "SOS" },
  { label: "SRD " + vm.$t("Currency.SRD"), value: "SRD" },
  { label: "SSP " + vm.$t("Currency.SSP"), value: "SSP" },
  { label: "STD " + vm.$t("Currency.STD"), value: "STD" },
  { label: "SVC " + vm.$t("Currency.SVC"), value: "SVC" },
  { label: "SYP " + vm.$t("Currency.SYP"), value: "SYP" },
  { label: "SZL " + vm.$t("Currency.SZL"), value: "SZL" },
  { label: "THB " + vm.$t("Currency.THB"), value: "THB" },
  { label: "TJS " + vm.$t("Currency.TJS"), value: "TJS" },
  { label: "TMT " + vm.$t("Currency.TMT"), value: "TMT" },
  { label: "TND " + vm.$t("Currency.TND"), value: "TND" },
  { label: "TOP " + vm.$t("Currency.TOP"), value: "TOP" },
  { label: "TRY " + vm.$t("Currency.TRY"), value: "TRY" },
  { label: "TTD " + vm.$t("Currency.TTD"), value: "TTD" },
  { label: "TWD " + vm.$t("Currency.TWD"), value: "TWD" },
  { label: "TZS " + vm.$t("Currency.TZS"), value: "TZS" },
  { label: "UAH " + vm.$t("Currency.UAH"), value: "UAH" },
  { label: "UGX " + vm.$t("Currency.UGX"), value: "UGX" },
  { label: "USD " + vm.$t("Currency.USD"), value: "USD" },
  { label: "UYU " + vm.$t("Currency.UYU"), value: "UYU" },
  { label: "UZS " + vm.$t("Currency.UZS"), value: "UZS" },
  { label: "VEF " + vm.$t("Currency.VEF"), value: "VEF" },
  { label: "VND " + vm.$t("Currency.VND"), value: "VND" },
  { label: "VUV " + vm.$t("Currency.VUV"), value: "VUV" },
  { label: "WST " + vm.$t("Currency.WST"), value: "WST" },
  { label: "XAF " + vm.$t("Currency.XAF"), value: "XAF" },
  { label: "XAG " + vm.$t("Currency.XAG"), value: "XAG" },
  { label: "XAU " + vm.$t("Currency.XAU"), value: "XAU" },
  { label: "XCD " + vm.$t("Currency.XCD"), value: "XCD" },
  { label: "XDR " + vm.$t("Currency.XDR"), value: "XDR" },
  { label: "XOF " + vm.$t("Currency.XOF"), value: "XOF" },
  { label: "XPD " + vm.$t("Currency.XPD"), value: "XPD" },
  { label: "XPF " + vm.$t("Currency.XPF"), value: "XPF" },
  { label: "XPT " + vm.$t("Currency.XPT"), value: "XPT" },
  { label: "YER " + vm.$t("Currency.YER"), value: "YER" },
  { label: "ZAR " + vm.$t("Currency.ZAR"), value: "ZAR" },
  { label: "ZMW " + vm.$t("Currency.ZMW"), value: "ZMW" },
  { label: "ZWL " + vm.$t("Currency.ZWL"), value: "ZWL" }
];

export const PAYMENT_METHOD_FFC = "ffc";
export const PAYMENT_METHOD_ALIPAY = "alipay";
export const PAYMENT_METHOD_WX = "wx";
export const PAYMENT_METHOD_BANK = "bank";

export const PAYMENT_METHODS_LIST = [
  PAYMENT_METHOD_FFC,
  PAYMENT_METHOD_ALIPAY,
  PAYMENT_METHOD_WX,
  PAYMENT_METHOD_BANK
];

export const PAYMENT_METHODS_LIST1 = [
  PAYMENT_METHOD_ALIPAY,
  PAYMENT_METHOD_WX,
  PAYMENT_METHOD_BANK
];

export const BANK_LIST = [
  { label: vm.$t("Bank.PINGAN"), value: "PINGAN" },
  { label: vm.$t("Bank.BC"), value: "BC" },
  { label: vm.$t("Bank.ICBC"), value: "ICBC" },
  { label: vm.$t("Bank.ABC"), value: "ABC" },
  { label: vm.$t("Bank.CBC"), value: "CBC" },
  { label: vm.$t("Bank.CMBC"), value: "CMBC" },
  { label: vm.$t("Bank.CEB"), value: "CEB" },
  { label: vm.$t("Bank.MSBC"), value: "MSBC" },
  { label: vm.$t("Bank.EXIMBC"), value: "EXIMBC" },
  { label: vm.$t("Bank.CITIC"), value: "CITIC" },
  { label: vm.$t("Bank.CIB"), value: "CIB" },
  { label: vm.$t("Bank.CDB"), value: "CDB" },
  { label: vm.$t("Bank.PBC"), value: "PBC" },
  { label: vm.$t("Bank.CTB"), value: "CTB" },
  { label: vm.$t("Bank.CUB"), value: "CUB" },
  { label: vm.$t("Bank.HXB"), value: "HXB" },
  { label: vm.$t("Bank.SPDB"), value: "SPDB" }
];
